name: 'Deploy function app to azure function'

on:
    push:
        branches:
            - githubactiontest
    workflow_dispatch:

jobs:

    build_deploy:
        runs-on: ubuntu-latest
        env:
            PYTHON_VERSION: '3.11'
            RESOURCE_GROUP_NAME: 'azpoe-hecmonitor-test'
            APP_NAME: 'azpoe-hecmonitor-nsgrtbackup'
            AZ_PATH: '.'
        steps:
            - name: 'Checkout Github Actions'
              uses: actions/checkout@v3

            - name: 'Azure Login'
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: 'Azure CLI'
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az account show

            - name: 'Setup Python Env'
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}

            - name: 'Create Virtual env'
              run: |
                python -m venv .venv
                source .venv/bin/activate

            - name: 'Install dependenices'
              run: |
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: 'Include Deployment File'
              run: |
                touch .deployment
                echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment

            - name: 'Check file path'
              run: |
                pwd
                cat .deployment
                ls -a

            - name: 'Zip function app'
              run: |
                zip -r nsgrtfunctionapp.zip ${{env.AZ_PATH}}  

            - name: 'Check if zip file is present'
              run: |
                ls -a

            - name: 'Deploy to function app'
              run: |
                az functionapp deployment source config-zip -g ${{env.RESOURCE_GROUP_NAME}} -n ${{env.APP_NAME}} --src ./nsgrtfunctionapp.zip



